In [1]:
# get information about the business or the organization
# know the problem at hand
# getting the right data
# EDA (exploratory data analysis)
  # data cleaning
  # data transformation
  # descriptive analysis (python, powerbi, tableau)
  # data visualization (python, powerbi, tableau)
# machine learning(python) (Linear regression, binary classification, multiclassification, clustering, text or sentiment analysis)
  # preprocessing
  # model building
  # Evaluation (verification)
# Deep learning

In [2]:
# NUMPY : NUMERICAL PYTHON
import numpy as np

In [3]:
arr1 = np.array([75,85,60,47])
arr1

array([75, 85, 60, 47])

In [4]:
arr1.ndim # checking the numbers of array dimension

1

In [5]:
arr1.shape

(4,)

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr2 = np.array([[47,85,69,60],[80,85,64,90]])
arr2

array([[47, 85, 69, 60],
       [80, 85, 64, 90]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 4)

In [10]:
arr2.dtype

dtype('int32')

In [11]:
# creating an array where all values are zero
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [12]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# creating an array where all values are one
np.ones(60)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones((5,5)) * 15

array([[15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.]])

In [16]:
# linspace - creating arrays that are evenly spaced over a specified interval
np.linspace(20,70)

array([20.        , 21.02040816, 22.04081633, 23.06122449, 24.08163265,
       25.10204082, 26.12244898, 27.14285714, 28.16326531, 29.18367347,
       30.20408163, 31.2244898 , 32.24489796, 33.26530612, 34.28571429,
       35.30612245, 36.32653061, 37.34693878, 38.36734694, 39.3877551 ,
       40.40816327, 41.42857143, 42.44897959, 43.46938776, 44.48979592,
       45.51020408, 46.53061224, 47.55102041, 48.57142857, 49.59183673,
       50.6122449 , 51.63265306, 52.65306122, 53.67346939, 54.69387755,
       55.71428571, 56.73469388, 57.75510204, 58.7755102 , 59.79591837,
       60.81632653, 61.83673469, 62.85714286, 63.87755102, 64.89795918,
       65.91836735, 66.93877551, 67.95918367, 68.97959184, 70.        ])

In [17]:
np.linspace(20,90)

array([20.        , 21.42857143, 22.85714286, 24.28571429, 25.71428571,
       27.14285714, 28.57142857, 30.        , 31.42857143, 32.85714286,
       34.28571429, 35.71428571, 37.14285714, 38.57142857, 40.        ,
       41.42857143, 42.85714286, 44.28571429, 45.71428571, 47.14285714,
       48.57142857, 50.        , 51.42857143, 52.85714286, 54.28571429,
       55.71428571, 57.14285714, 58.57142857, 60.        , 61.42857143,
       62.85714286, 64.28571429, 65.71428571, 67.14285714, 68.57142857,
       70.        , 71.42857143, 72.85714286, 74.28571429, 75.71428571,
       77.14285714, 78.57142857, 80.        , 81.42857143, 82.85714286,
       84.28571429, 85.71428571, 87.14285714, 88.57142857, 90.        ])

In [18]:
np.linspace(20,50)

array([20.        , 20.6122449 , 21.2244898 , 21.83673469, 22.44897959,
       23.06122449, 23.67346939, 24.28571429, 24.89795918, 25.51020408,
       26.12244898, 26.73469388, 27.34693878, 27.95918367, 28.57142857,
       29.18367347, 29.79591837, 30.40816327, 31.02040816, 31.63265306,
       32.24489796, 32.85714286, 33.46938776, 34.08163265, 34.69387755,
       35.30612245, 35.91836735, 36.53061224, 37.14285714, 37.75510204,
       38.36734694, 38.97959184, 39.59183673, 40.20408163, 40.81632653,
       41.42857143, 42.04081633, 42.65306122, 43.26530612, 43.87755102,
       44.48979592, 45.10204082, 45.71428571, 46.32653061, 46.93877551,
       47.55102041, 48.16326531, 48.7755102 , 49.3877551 , 50.        ])

In [19]:
np.eye(6) 

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
arr4 = np.arange(1,101)
arr4

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [21]:
arr4 = np.arange(1,101,5) # adding that five means it must take a step of five before the next value, same with other numbers
arr4

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [22]:
arr4 = np.arange(1,101,10)
arr4

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [23]:
arr5 = np.random.randint(15,105,100)
arr5

array([ 95,  75, 100,  83,  90,  35,  64,  40, 104,  43,  54,  18,  33,
        73,  96,  63,  21,  92,  35,  62,  45,  62,  86,  75,  39,  42,
        16,  80,  45,  86,  89,  68,  62,  62,  71, 101,  55,  75,  79,
        60,  84,  32,  20,  67,  74,  50,  22,  27,  99,  31,  50,  77,
        83,  24,  44,  97,  46,  61,  92,  62,  83,  78,  35,  77,  57,
        22,  96,  77,  94, 102,  35,  88,  88,  54,  66,  66, 100,  45,
        27,  98,  19,  42,  35,  81,  32,  98,  48,  41,  54, 101,  67,
        95,  54,  57,  90,  71,  38,  97,  57,  32])

In [25]:
np.random.seed(5)
arr5 = np.random.randint(15,105,100)
arr5

array([ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22,  91,  30,  68,
        95,  42,  59,  92,  90,  80,  62,  45,  99, 101,  33,  24,  56,
        77,  16,  97,  31,  93,  20,  73,  15,  95,  19,  51,  66,  42,
        46,  17,  83,  53,  98,  34,  33,  22,  45,  77,  26,  82,  80,
        70,  18,  93,  42,  44,  48, 104, 100,  22,  31,  29,  46,  24,
        53,  62,  31,  20,  49,  60,  74,  39,  28,  46,  47,  91,  59,
        20,  29,  62,  97,  15,  22, 101,  31,  79,  23,  59,  52,  90,
        20,  37,  67,  84,  97,  75,  44, 103,  94])

In [26]:
arr6 = arr5.reshape(10,10)
arr6

array([[ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22],
       [ 91,  30,  68,  95,  42,  59,  92,  90,  80,  62],
       [ 45,  99, 101,  33,  24,  56,  77,  16,  97,  31],
       [ 93,  20,  73,  15,  95,  19,  51,  66,  42,  46],
       [ 17,  83,  53,  98,  34,  33,  22,  45,  77,  26],
       [ 82,  80,  70,  18,  93,  42,  44,  48, 104, 100],
       [ 22,  31,  29,  46,  24,  53,  62,  31,  20,  49],
       [ 60,  74,  39,  28,  46,  47,  91,  59,  20,  29],
       [ 62,  97,  15,  22, 101,  31,  79,  23,  59,  52],
       [ 90,  20,  37,  67,  84,  97,  75,  44, 103,  94]])

In [27]:
arr6[4,5] # selecting a particular number from the values. count the rows and columns starting from 0

33

In [28]:
arr6[3:7,3:6] # selecting various numbers

array([[15, 95, 19],
       [98, 34, 33],
       [18, 93, 42],
       [46, 24, 53]])

In [29]:
arr6[3:7,3:6] = 100  # broadcasting - means to change all the values to a single value
arr6

array([[ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22],
       [ 91,  30,  68,  95,  42,  59,  92,  90,  80,  62],
       [ 45,  99, 101,  33,  24,  56,  77,  16,  97,  31],
       [ 93,  20,  73, 100, 100, 100,  51,  66,  42,  46],
       [ 17,  83,  53, 100, 100, 100,  22,  45,  77,  26],
       [ 82,  80,  70, 100, 100, 100,  44,  48, 104, 100],
       [ 22,  31,  29, 100, 100, 100,  62,  31,  20,  49],
       [ 60,  74,  39,  28,  46,  47,  91,  59,  20,  29],
       [ 62,  97,  15,  22, 101,  31,  79,  23,  59,  52],
       [ 90,  20,  37,  67,  84,  97,  75,  44, 103,  94]])

In [30]:
arr7 = arr6.flatten() # returning 2D to 1D
arr7

array([ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22,  91,  30,  68,
        95,  42,  59,  92,  90,  80,  62,  45,  99, 101,  33,  24,  56,
        77,  16,  97,  31,  93,  20,  73, 100, 100, 100,  51,  66,  42,
        46,  17,  83,  53, 100, 100, 100,  22,  45,  77,  26,  82,  80,
        70, 100, 100, 100,  44,  48, 104, 100,  22,  31,  29, 100, 100,
       100,  62,  31,  20,  49,  60,  74,  39,  28,  46,  47,  91,  59,
        20,  29,  62,  97,  15,  22, 101,  31,  79,  23,  59,  52,  90,
        20,  37,  67,  84,  97,  75,  44, 103,  94])

In [31]:
np.sum(arr7)

6311

In [32]:
np.max(arr7)

104

In [33]:
np.min(arr7)

15

In [34]:
np.percentile(arr7,50)

62.0

In [35]:
np.argmax(arr7) # return the value of the max location means it will find the location of the first 104 it can find

58

In [ ]:
# to understand 